#ifndef SHAREDDEFINES_H
#define SHAREDDEFINES_H

enum Direction
{
    DIRECTION_NONE   = 0x00,
    DIRECTION_UP     = 0x01,
    DIRECTION_DOWN   = 0x02,
    DIRECTION_LEFT   = 0x04,
    DIRECTION_RIGHT  = 0x08,

    DIRECTION_UPLEFT = DIRECTION_UP | DIRECTION_LEFT,
    DIRECTION_UPRIGHT = DIRECTION_UP | DIRECTION_RIGHT,
    DIRECTION_DOWNLEFT = DIRECTION_DOWN | DIRECTION_LEFT,
    DIRECTION_DOWNRIGHT = DIRECTION_DOWN | DIRECTION_RIGHT,
};

// side and direction values beeing the same is intentional!
enum Side
{
    SIDE_NONE = DIRECTION_NONE,
    SIDE_TOP = DIRECTION_UP,
    SIDE_BOTTOM = DIRECTION_DOWN,
    SIDE_LEFT = DIRECTION_LEFT,
    SIDE_RIGHT = DIRECTION_RIGHT,

    SIDE_TOPLEFT = SIDE_TOP | SIDE_LEFT,
    SIDE_TOPRIGHT = SIDE_TOP | SIDE_RIGHT,
    SIDE_BOTTOMLEFT = SIDE_TOP | SIDE_LEFT,
    SIDE_BOTTOMRIGHT = SIDE_TOP | SIDE_RIGHT
};


#endif
