#ifndef SHAREDDEFINES_H
#define SHAREDDEFINES_H

enum Direction
{
    DIRECTION_NONE   = 0x00,
    DIRECTION_UP     = 0x01,
    DIRECTION_DOWN   = 0x02,
    DIRECTION_LEFT   = 0x04,
    DIRECTION_RIGHT  = 0x08,

    DIRECTION_UPLEFT = DIRECTION_UP | DIRECTION_LEFT,
    DIRECTION_UPRIGHT = DIRECTION_UP | DIRECTION_RIGHT,
    DIRECTION_DOWNLEFT = DIRECTION_DOWN | DIRECTION_LEFT,
    DIRECTION_DOWNRIGHT = DIRECTION_DOWN | DIRECTION_RIGHT,
};


#endif
